/* App */
export const LOADING = 'LOADING'
export const REQUEST_CHANGE_THEME = 'REQUEST_CHANGE_THEME'
export const CHANGE_THEME = 'CHANGE_THEME'
export const ERROR = 'ERROR'
export const SHOW_ERROR = 'SHOW_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const FETCHING_NOTES = 'FETCHING_NOTES'
export const NOTES_FETCHED = 'NOTES_FETCHED'
export const LOCAL_NOTES_SET = 'LOCAL_NOTES_SET'
export const ADDING_NOTE = 'ADDING_NOTE'
export const UPDATING_NOTE = 'UPDATING_NOTE'
export const DELETING_NOTE = 'DELETING_NOTE'
export const UPLOADING_FILE = 'UPLOADING_FILE'
export const DOWNLOADING_FILE = 'DOWNLOADING_FILE'

/* User */
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const SET_NAME = 'SET_NAME'
export const UPDATE = 'UPDATE'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const LOGOUT = 'LOGOUT'

/* Notes */
export const FETCH_NOTES = 'FETCH_NOTES'
export const SET_NOTES = 'SET_NOTES'
export const REQUEST_ADD_NOTE = 'REQUEST_ADD_NOTE'
export const ADD_NOTE = 'ADD_NOTE'
export const REQUEST_UPDATE_NOTE = 'REQUEST_UPDATE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const REQUEST_DELETE_NOTE = 'REQUEST_DELETE_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'

/* Files */
export const FETCH_FILES = 'FETCH_FILES'
export const SET_FILES = 'SET_FILES'
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const ADD_FILE = 'ADD_FILE'
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE'
export const ADD_ATTACHMENT = 'ADD_ATTACHMENT'
