export const VIEWPORT_4 = '(min-width: 480px)'
export const VIEWPORT_7 = '(min-width: 768px)'
export const VIEWPORT_9 = '(min-width: 992px)'
export const VIEWPORT_12 = '(min-width: 1200px)'
export const NOT_MOBILE = '(hover: hover) and (pointer: fine)'
